# Generated by Django 3.1 on 2020-08-12 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='calories',
        ),
    ]
